config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get 'dashboard', to: "users#show"
  resources :projects do
    resources :images
  end
  resources :agencies, only: [ :edit, :update, :destroy ]
  resources :messages
end

app/models/agency.rb
class Agency < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project
  mount_uploader :url, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  validates :from_email_address, presence: true
  validates_format_of :from_email_address, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :from_tel, presence: true, format: { with: /[\+\d]{9,}/, message: "should only contain digits and '+'" }
  validates :subject, length: { minimum: 3, maximum: 50 }
  validates :message, length: { minimum: 20, maximum: 500 }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :images, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # :registerable,
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :find_agency, only: [ :edit, :update ]

  def edit
    authorize @agency
  end

  def update
    authorize @agency
    @agency.update(agency_params)
    redirect_to dashboard_path
  end

  private

  def agency_params
    params.require(:agency).permit(:text, :address, :email, :phone)
  end

   def find_agency
    @agency = Agency.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [ :destroy ]

  def new
    @image = Image.new
    @project = Project.find(params[:project_id])
    authorize @image
  end

  def create
    @image = Image.new(image_params)
    authorize @image
    @image.project = Project.find(params[:project_id])
    if @image.save
      redirect_to project_path(@image.project)
    else
      render new_project_image_path
    end
  end

  def destroy
    @image.destroy
    authorize @image
    @project = @image.project

    redirect_to project_path(@project)
  end

  private

  def image_params
    params.require(:image).permit(:url)
  end

  def find_image
    @image = Image.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create ]
  before_action :find_message, only: [ :show, :destroy ]

  def show
    authorize @message
    @message.update(state: true)
  end

  def new
    @new_message = Message.new
    authorize @new_message
  end

  def create
    @new_message = Message.new(message_params)
    authorize @new_message

    if @new_message.save
      # respond_to do |format|
      #   format.html { redirect_to root_path }
      #   format.js # <-- will render `app/views/new_messages/create.js.erb`
      # end
      flash[:success] = "Merci pour votre message,
                         nous vous contacterons dès
                         que possible!"

      redirect_to root_path
    else
      render new_message_path
    end
  end

  def destroy
    @message = Message.find(params[:id])
    authorize @message
    @message.destroy

    redirect_to dashboard_path
  end

  private

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:from_email_address, :from_tel, :subject, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @projects = Project.all
    @agency = Agency.first
    @agency_address = Agency.first.address.split(',')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]
  before_action :find_project, only: [ :show, :edit, :update, :destroy ]

  def show
    authorize @project
  end

  def new
    @project = Project.new
    @project.images.build
    authorize @project
  end

  def create
    @new_project = Project.new(project_params)
    authorize @new_project
    if @new_project.save
      redirect_to project_path(@new_project)
    else
      render new_project_path
    end
  end

  def edit
    authorize @project
    @image = Image.where(project_id: params[:id])
  end

  def update
    authorize @project
    @project.update(project_params)

    redirect_to project_path(@project)
  end

  def destroy
    authorize @project
    @project.destroy

    redirect_to dashboard_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :type_1, :type_2, :description, :content, :state)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.where(admin: true)
    authorize @user
    @messages = Message.all.order(created_at: :desc)
    @projects = policy_scope(Project).order(created_at: :desc)
    @agency = Agency.first
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/agencies/edit.html.erb
<h1>Edit agency infos</h1>
<div class="container">
  <%= simple_form_for @agency do |f| %>
    <%= f.input :text, :input_html => { 'rows' => 5} %>
    <%= f.input :address %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'Back to Dashboard', dashboard_path %>
</div>

app/views/images/new.html.erb
<div class="new-image-container">
  <%= simple_form_for ([@project, @image]) do |f| %>
    <%= f.file_field :url %>
    <%= f.input :url_cache, as: :hidden %>
    <%= f.button :submit, class: 'action-btn green-btn' %>
  <% end %>
  <%= link_to project_path(@project) do %>
    Back to <strong><%= @project.title %></strong> view
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>OPB | Architecture | Urbanisme</title>
    <meta name="description" content="Agence d'architecture Olivier Pozzo Di Borgo"/>
    <meta name="keywords" content="architecture, architect, corse, architecture corse, architect corse, biguglia, bastia, architect bastia, architect biguglia, OPB, Olivier Pozzo Di Borgo, urbanisme, urbanisme corse" />

    <link rel="apple-touch-icon" href="img/OPB-mini.png" />

    <meta property="og:title" content="OPB Architecture" />
    <meta property="og:type" content="site web" />
    <meta property="og:url" content="http://opb-architecture.com"/>
    <meta property="og:image" content="images/OPB-mini.png" />
    <meta property="og:description" content="Agence d'architecture Olivier Pozzo Di Borgo"/>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key} flash-message") %>
    <% end %>
    <%= yield %>
  <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/create.js.erb
const containerMessage = document.querySelector('.container-message');

containerMessage.innerHTML = `<div>
                                <p>Merci pour votre message,
                                nous vous contacterons dès que possible!<p>
                              </div>`

app/views/messages/new.html.erb
<a href="/" class="close-button"></a>
<%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-list-projects') %>
<div class="container-message">
  <%= simple_form_for @new_message do |f| %>
    <%= f.error_notification %>
    <%= f.input :from_email_address, label: 'Adresse email' %><%= f.input :from_tel, label: 'Télephone' %>
    <%= f.input :subject, label: 'Object' %>
    <%= f.input :message %>
    <%= f.button :submit, value: 'Envoyer' %>
  <% end %>
</div>

<script>
  $('#envoyer-message').click(function() {
    alert('Merci pour votre message!');
  });
</script>

app/views/messages/show.html.erb
<div class="container">
  <p><strong>Date: </strong><%= @message.created_at.strftime("%B %d, %Y, %H:%M") %></p>
  <p><strong>Subject: </strong><%= @message.subject %></p>
  <p><strong>Message: </strong><%= @message.message %></p>
  <% if policy(@message).destroy? %>
    <%= link_to message_path(@message), :method => :delete, :data => {:confirm => "Are you sure to delete this message Mr Oli Pozzo?"} do %>
      <i class="far fa-trash-alt"></i> Delete
    <% end %>
  <% end %>
  <%= link_to 'Back to dashboard', dashboard_path %>
</div>

app/views/pages/index.html.erb
<%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-index-page') %>

<%= render 'shared/fullpage_page' %>

<div class="arrow-up-circle">
  <div class="arrow-up arrow-up-animated"></div>
  <div class="arrow-up arrow-up"></div>
</div>
<div class="arrow-down-circle">
  <div class="arrow-down arrow-down-animated"></div>
  <div class="arrow-down arrow-down"></div>
</div>

<div class="arrow-top-0">
  <div class="arrow-up-animated arrow-up"></div>
  <p>Top</p>
</div>

<script>
const body = document.querySelector('body');
let fullPage = document.getElementById('fullpage');

const navbars = document.querySelectorAll('.navbar');
const agencyButtons = document.querySelectorAll('.agence-nav');
const projectsButtons = document.querySelectorAll('.projets-nav');
const contactButtons = document.querySelectorAll('.contact-nav');

const circleArrowDown = document.querySelector('.arrow-down-circle');
const circleArrowUp = document.querySelector('.arrow-up-circle');
const arrowTop = document.querySelector('.arrow-top-0');

let fadeOutInterval = null;

function defFadeOutInterval(from_page, to_page) {
  fadeOutInterval = setInterval(function(){fadeOut(from_page, to_page)}, 20);
  fadeOutIndex = 1;
}

let fadeOutIndex = 1;

function fadeOut(from_page, to_page) {

  let newPage = null;
  let from_pageHTML = null;

  fadeOutIndex -= 0.05;

  if ( to_page === 'agency' ) {
    newPage = `<%= render 'shared/agency_page' %>`;
    from_pageHTML = fullPage;

    navbars.forEach(function(navbar){
      navbar.style.opacity = fadeOutIndex - 0.5;
      navbar.style.zIndex = 0;
    });

    circleArrowDown.style.opacity = fadeOutIndex - 0.5;
    circleArrowUp.style.opacity = fadeOutIndex - 0.5;
    arrowTop.style.opacity = fadeOutIndex - 0.5;

  } else if ( to_page === 'listProjects' ) {
    newPage = `<%= render 'shared/list_projects' %>`;
    from_pageHTML = fullPage;

    navbars.forEach(function(navbar){
      navbar.style.opacity = fadeOutIndex - 0.5;
      navbar.style.zIndex = 0;
    });

    circleArrowDown.style.opacity = fadeOutIndex - 0.5;
    circleArrowUp.style.opacity = fadeOutIndex - 0.5;
    arrowTop.style.opacity = fadeOutIndex - 0.5;

  } else if ( to_page === 'contact' ) {
    newPage = `<%= render 'shared/contact_page' %>`;
    from_pageHTML = fullPage;

    navbars.forEach(function(navbar){
      navbar.style.opacity = fadeOutIndex - 0.5;
      navbar.style.zIndex = 0;
    });

    circleArrowDown.style.opacity = fadeOutIndex - 0.5;
    circleArrowUp.style.opacity = fadeOutIndex - 0.5;
    arrowTop.style.opacity = fadeOutIndex - 0.5;

  } else {
    newPage = fullPage;
    if ( from_page === 'agency' ) {
      from_pageHTML = document.getElementById('agency');
    } else if ( from_page === 'listProjects' ) {
      from_pageHTML = document.getElementById('list-projects');
    } else if ( from_page === 'contact' ) {
      from_pageHTML = document.getElementById('contact');
    }
  }

  from_pageHTML.style.opacity = fadeOutIndex;

  if (fadeOutIndex <= 0) {
    clearInterval(fadeOutInterval);
    changeHtml(from_pageHTML, newPage);
  }
}


function changeHtml(from_page, newPage) {
  let pageHtml = null;

  if ( from_page === fullPage ) {
    body.insertAdjacentHTML('beforeend', newPage);
  } else {
    from_page.parentNode.removeChild(from_page);
    pageHtml = newPage;
  }


  agency = document.getElementById('agency');
  listProjects = document.getElementById('list-projects');
  contact = document.getElementById('contact');

  if ( agency != null ) {
    pageHtml = agency;
  }

  if ( listProjects != null ) {
    pageHtml = listProjects;
  }

  if ( contact != null ) {
    pageHtml = contact;
  }

  defDisplayInterval(from_page, pageHtml);
}

let displayInterval = null;

let displayIndex = -0.5;

function defDisplayInterval(from_page, to_page) {
  displayInterval = setInterval(function(){display(from_page, to_page)}, 50);
  displayIndex = 0;
}

function display(from_page, to_page) {
  displayIndex += 0.05;
  to_page.style.opacity = displayIndex;

  if ( to_page === fullPage ) {

    navbars.forEach(function(navbar){
      navbar.style.zIndex = 9;
      navbar.style.opacity = displayIndex;
    });

    circleArrowDown.style.opacity = displayIndex;
    circleArrowUp.style.opacity = displayIndex;
    arrowTop.style.opacity = displayIndex;
  }

  if (displayIndex > 1) {
    clearInterval(displayInterval);

    const closingCrossAgency = document.getElementById('closing-cross-agency');
    const closingCrossProjectList = document.getElementById('closing-cross-list-projects');
    const closingCrossContact = document.getElementById('closing-cross-contact');

    if ( closingCrossAgency != null ) {
      closingCrossAgency.addEventListener('click', function(){defFadeOutInterval('agency', fullPage)});
    }

    if ( closingCrossProjectList != null ) {
      closingCrossProjectList.addEventListener('click', function(){defFadeOutInterval('listProjects', fullPage)});
    }

    if ( closingCrossContact != null ) {
      closingCrossContact.addEventListener('click', function(){defFadeOutInterval('contact', fullPage)});
    }
  }
}


agencyButtons.forEach(function(agencyButton) {
  agencyButton.addEventListener('click', function(){defFadeOutInterval(fullPage, 'agency')});
})

projectsButtons.forEach(function(projectsButton) {
  projectsButton.addEventListener('click', function(){defFadeOutInterval(fullPage, 'listProjects')});
})

contactButtons.forEach(function(contactButton) {
  contactButton.addEventListener('click', function(){defFadeOutInterval(fullPage, 'contact')});
})


</script>

<%= javascript_pack_tag 'home-constructor' %>

app/views/projects/_form.html.erb
<div class="container">
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :type_1 %>
    <%= f.input :type_2 %>
    <%= f.input :description %>
    <%= f.input :content, :input_html => { 'rows' => 5} %>
    <%= f.input :state, collection: [ "En cours", "Terminé" ] %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= render 'form' %>
<%= link_to 'Back to Dashboard', dashboard_path %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>
<%= render 'form' %>
<%= link_to 'Back to Dashboard', dashboard_path %>

app/views/projects/show.html.erb
<a href="/" class="close-button"></a>
<%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-list-projects') %>
<div class="buttons">
  <% if policy(@project).edit? %>
    <%= link_to "Edit", edit_project_path(@project), class: 'action-btn green-btn' %>
  <% end %>
  <% if policy(Image).new? %>
    <%= link_to 'Add Image', new_project_image_path(@project), class: 'action-btn green-btn' %>
  <% end %>
  <% if policy(@project).destroy? %>
    <%= link_to "Delete", project_path(@project), :method => :delete, :data => {:confirm => "Are you sure Mr Oli Pozzo?"}, class: 'action-btn red-btn' %>
  <% end %>
  <% if policy(User).show? %>
    <%= link_to 'Back to dashboard', dashboard_path %>
  <% end %>
</div>
<div class="projects-container">
  <div class="row project-presentation project">
    <% if @project.images.first.nil? %>
      <div class="col-xs-12 col-sm-6 images-container">
          <div class="image-active" >
            <p>Sorry no pictures</p>
          </div>
    <% else %>
      <div class="col-xs-12 col-md-6 images-container animate-reveal animate-first">
        <div class="image-active w3-">
          <% @project.images.each do |image| %>
            <%= cl_image_tag image.url, class: "mySlides" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-12 col-md-6 text-container animate-reveal animate-second">
      <h3 class="title-project text-animate"><%= @project.title %></h3>
      <h5 class="description-project text-animate"><%= @project.description %></h5>
      <p class="type_1-project text-animate"><strong><%= @project.type_1 %> - <%= @project.type_2 %></strong></p>
      <p class="content-project text-animate"><%= @project.content %></p>
      <div class="images-mozaic row animate-reveal animate-third">
        <% index_image_section = 0 %>
        <% @project.images.each do |image| %>
          <% index_image_section += 1 %>
          <div class="col-xs-6 image-mozaic-box">
            <%= cl_image_tag image.url, class: "demo w3-opacity w3-hover-opacity-off demo-images", :onclick=> "currentDiv(#{index_image_section})" %>
            <br>
            <% if policy(image).destroy? %>
              <%= link_to "Delete image", project_image_path(@project, image), :method => :delete, :data => {:confirm => "Are you sure Mr Oli Pozzo?"} %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <script>
    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
      showDivs(slideIndex += n);
    }

    function currentDiv(n) {
      showDivs(slideIndex = n);
    }

    function showDivs(n) {
      var i;
      var x = document.getElementsByClassName(`mySlides`);
      var dots = document.getElementsByClassName(`demo`);
      if (n > x.length) {slideIndex = 1}
      if (n < 1) {slideIndex = x.length}
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
      }
      x[slideIndex-1].style.display = "block";
      dots[slideIndex-1].className += " w3-opacity-off";
    }
  </script>
  </div>
</div>

app/views/shared/_agency_page.html.erb
<div class="container-agency" id="agency">
  <%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-agency-page') %>
  <span class="close-button" id="closing-cross-agency"></span>
  <div class="agency-intro">
    <h3 class="animate-reveal animate-first">L'agence</h3>
    <p class="animate-reveal animate-second"><%= @agency.text %></p>
  </div>
</div>

app/views/shared/_arrow_down.html.erb
<div class="arrow-down-circle" data-arrow-down="1">
  <div class="arrow-down arrow-down-animated"></div>
  <div class="arrow-down arrow-down"></div>
</div>

app/views/shared/_arrow_left.html.erb
<div class="arrow-left-circle">
  <div class="arrow-left arrow-left"></div>
  <div class="arrow-left arrow-left-animated"></div>
</div>

app/views/shared/_arrow_right.html.erb
<div class="arrow-right-circle">
  <div class="arrow-right arrow-right-animated"></div>
  <div class="arrow-right arrow-right"></div>
</div>

app/views/shared/_arrow_up.html.erb
<div class="arrow-up-circle" data-arrow-up="1">
  <div class="arrow-up arrow-up-animated"></div>
  <div class="arrow-up arrow-up"></div>
</div>

app/views/shared/_closing_cross.html.erb
<span class="close-button"></span>

app/views/shared/_contact_page.html.erb
<div class="container-contact" id="contact">
  <%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-contact-page') %>
  <span class="close-button" id="closing-cross-contact"></span>
  <div class="agency-intro">
    <h3 class="animate-reveal animate-first">Contact</h3>
    <p class="address animate-reveal animate-second"><%= @agency_address[2] %></p>
    <p class="address animate-reveal animate-second"><%= @agency_address[1] %></p>
    <p class="address animate-reveal animate-second"><strong><%= @agency_address[0] %></strong></p>
    <p class="email-address-agency animate-reveal animate-second"><%= @agency.email %> - <%= @agency.phone %></p>
    <%= link_to 'Envoyer un message', new_message_path, target: '_blank', class: 'animate-reveal animate-third' %>
  </div>
</div>

app/views/shared/_fullpage_page.html.erb
<div class="info-opb-right navbar">
  <ul>
    <li><i class="fas fa-plus-circle agence-nav"></i> <div class="nav-item"><span class="nav-label"> Agence</span></div></li>
    <li><i class="fas fa-plus-circle projets-nav"></i> <div class="nav-item"><span class="nav-label"> Projets</span></div></li>
    <li><i class="fas fa-plus-circle contact-nav"></i> <div class="nav-item"><span class="nav-label"> Contact</span></div></li>
  </ul>
</div>

<div class="custom-dropdown navbar">
  <i class="fa fa-bars" id="icon-dropdown" style="font-size: 40px;"></i>
  <ul id="list-dropdown">
    <li><i class="fas fa-plus-circle agence-nav"></i> <div class="nav-item"><span class="nav-label"> Agence</span></div></li>
    <li><i class="fas fa-plus-circle projets-nav"></i> <div class="nav-item"><span class="nav-label"> Projets</span></div></li>
    <li><i class="fas fa-plus-circle contact-nav"></i> <div class="nav-item"><span class="nav-label"> Contact</span></div></li>
  </ul>
</div>

<div id="fullpage">
  <div class="banner-index section" data-index-section="0">
    <div class="info-opb-left">
      <%= render 'shared/logo_final' %>
    </div>
  </div>
  <%= render 'shared/projects' %>
</div>

app/views/shared/_list_projects.html.erb
<div class="container-list-projects" id="list-projects">
  <%= image_tag("LOGO-FINAL-01.png", :alt => "logo-opb", width: 250, class: 'logo-list-projects') %>
  <ul>
    <span class="close-button" id="closing-cross-list-projects"></span>
    <% @projects.each do |project| %>
      <li class="animate-reveal animate-first"><%= link_to project.title, project_path(project), target: '_blank' %></li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<h1 class="text-center">Oli Pozzo DashBoard</h1>
  <h3 class="messages-box-intro">Salut Olivier, tu as <strong><%= @messages.count %></strong> dont <strong><%= @messages.where(state: false).count %></strong>  que tu n'as pas encore lu!</h3>
  <div class="dashboard-container-message">
    <% @messages.each do |message| %>
      <% if message.state %>
        <div class="row dashboard-messages" style="background-color: #fff">
      <% else %>
        <div class="row dashboard-messages">
      <% end %>
          <div class="col-xs-3">
            <p><strong><%= message.created_at.strftime("%B %d, %Y, %H:%M")%></strong></p>
          </div>
          <div class="col-xs-5">
            <p><%= message.subject %></p>
          </div>
          <div class="col-xs-4 action-column">
            <% if policy(message).show? %>
              <%= link_to message_path(message) do %>
                <i class='fas fa-eye'></i> Details
              <% end %>
            <% end %>
            <% if policy(message).destroy? %>
              <%= link_to message_path(message), :method => :delete, :data => {:confirm => "Are you sure to delete this message Mr Oli Pozzo?"} do %>
                <i class="far fa-trash-alt"></i> Delete
              <% end %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>

<div class="dashboard-container-agency">
  <h2>L'agence</h2>
  <div class="white-box">
    <p><strong>Text:</strong></p>
    <p><%= @agency.text %></p>
    <p><strong>Address:</strong></p>
    <p><%= @agency.address %></p>
    <p><strong>Email:</strong></p>
    <p><%= @agency.email %></p>
    <p><strong>Phone:</strong></p>
    <p><%= @agency.phone %></p>
    <% if policy(@agency).edit? %>
      <%= link_to edit_agency_path(@agency) do %>
        <i class="far fa-edit"></i> Edit
      <% end %>
    <% end %>
  </div>
</div>

<div class="dashboard-container-project">
  <h2>All projects</h2>
  <% i = 0 %>
  <% @projects.each do |project| %>
    <% i += 1 %>
    <div class="row dashboard-projects" data-index="<%= i %>">
      <div class="col-xs-3">
        <p><strong><%= project.title %></strong></p>
      </div>
      <div class="col-xs-5">
        <p><%= project.description %></p>
      </div>
      <div class="col-xs-4 action-column">
        <% if policy(project).show? %>
          <%= link_to project_path(project) do %>
            <i class='fas fa-eye'></i> Details
          <% end %>
        <% end %>
        <% if policy(project).edit? %>
          <%= link_to edit_project_path(project) do %>
            <i class="far fa-edit"></i> Edit
          <% end %>
        <% end %>
        <% if policy(project).destroy? %>
          <%= link_to project_path(project), :method => :delete, :data => {:confirm => "Are you sure to delete this project Mr Oli Pozzo?"} do %>
            <i class="far fa-trash-alt"></i> Delete
          <% end %>
        <% end %>
      </div>

    </div>
  <% end %>

  <div class="buttons">
    <%= link_to new_project_path, class: 'action-btn green-btn' do %>
      New Project <i class="fas fa-plus"></i>
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete do %>
      <%= t(".sign_out", default: "Log out") %>
    <% end %>

    <%= link_to root_path, targer: '_blank' do %>
      <i class="fas fa-desktop"></i> Go to website
    <% end %>
  </div>
</div>